FROM node:22-alpine
WORKDIR /app

COPY package*.json ./
COPY apps/api/package*.json ./apps/api/

# Dependências para compilação de módulos nativos (ex: bcrypt)
RUN apk add --no-cache python3 make g++

RUN npm install

COPY . .
RUN cd apps/api && npx prisma generate

ENV PORT=3001
EXPOSE 3001
CMD ["npm", "run", "start:dev", "--workspace=api"]
