FROM node:22-alpine
WORKDIR /app

COPY package*.json ./
COPY apps/api/package*.json ./apps/api/
RUN npm install

COPY . .
RUN cd apps/api && npx prisma generate

ENV PORT=3001
EXPOSE 3001
CMD ["npm", "run", "start:dev", "--workspace=api"]
